/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Expose } from "class-transformer";

/**
 * The response object for a delete operation
 */
export class DeleteResponse extends SpeakeasyBase {
    /**
     * Indicates whether the object was deleted or not
     */
    @SpeakeasyMetadata()
    @Expose({ name: "deleted" })
    deleted?: boolean;
}
