/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Expose, Type } from "class-transformer";

/**
 * The feedback JSON with one or many feedback items
 */
export class FeedbackQueryFeedbackJson extends SpeakeasyBase {}

/**
 * The request object for providing feedback
 */
export class FeedbackQuery extends SpeakeasyBase {
    /**
     * The feedback JSON with one or many feedback items
     */
    @SpeakeasyMetadata()
    @Expose({ name: "feedback_json" })
    @Type(() => FeedbackQueryFeedbackJson)
    feedbackJson?: FeedbackQueryFeedbackJson;

    /**
     * The ID of the generation for which feedback is being submitted
     */
    @SpeakeasyMetadata()
    @Expose({ name: "generation_id" })
    generationId?: string;

    /**
     * The ground truth for the generation
     */
    @SpeakeasyMetadata()
    @Expose({ name: "ground_truth" })
    groundTruth?: string;

    /**
     * The task for which the feedback is being submitted
     */
    @SpeakeasyMetadata()
    @Expose({ name: "task" })
    task?: string;
}
