/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Expose } from "class-transformer";

export class MetricCreateResponse extends SpeakeasyBase {
    /**
     * Boolean flag representing whether the metric was successfully inserted
     */
    @SpeakeasyMetadata()
    @Expose({ name: "inserted" })
    inserted?: boolean;
}
