/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Expose } from "class-transformer";

/**
 * The request object for creating a metric
 */
export class MetricRequest extends SpeakeasyBase {
    /**
     * The code snippet for the metric
     */
    @SpeakeasyMetadata()
    @Expose({ name: "code_snippet" })
    codeSnippet?: string;

    /**
     * The name of the metric
     */
    @SpeakeasyMetadata()
    @Expose({ name: "name" })
    name?: string;

    /**
     * The task related to the metric
     */
    @SpeakeasyMetadata()
    @Expose({ name: "task" })
    task?: string;
}
