/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Expose, Type } from "class-transformer";

export class PromptUpdateQueryFewShotExamples extends SpeakeasyBase {}

/**
 * The request object for updating a prompt
 */
export class PromptUpdateQuery extends SpeakeasyBase {
    /**
     * The few shot examples for the prompt
     */
    @SpeakeasyMetadata({ elemType: PromptUpdateQueryFewShotExamples })
    @Expose({ name: "few_shot_examples" })
    @Type(() => PromptUpdateQueryFewShotExamples)
    fewShotExamples?: PromptUpdateQueryFewShotExamples[];

    /**
     * The hyperparameters for the prompt
     */
    @SpeakeasyMetadata()
    @Expose({ name: "hyperparameters" })
    hyperparameters?: Record<string, any>;

    /**
     * The ID of the prompt
     */
    @SpeakeasyMetadata()
    @Expose({ name: "id" })
    id?: string;

    /**
     * The input variables to feed into the prompt
     */
    @SpeakeasyMetadata()
    @Expose({ name: "input_variables" })
    inputVariables?: string[];

    /**
     * Flag indicating if the prompt is deployed
     */
    @SpeakeasyMetadata()
    @Expose({ name: "is_deployed" })
    isDeployed?: boolean;

    /**
     * The model to be used for the prompt
     */
    @SpeakeasyMetadata()
    @Expose({ name: "model" })
    model?: string;

    /**
     * The version of the prompt
     */
    @SpeakeasyMetadata()
    @Expose({ name: "version" })
    version?: string;
}
