/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Expose, Type } from "class-transformer";

export class PromptCreationQueryFewShotExamples extends SpeakeasyBase {}

/**
 * The request object for creating a prompt
 */
export class PromptCreationQuery extends SpeakeasyBase {
    /**
     * The text of the chat prompt
     */
    @SpeakeasyMetadata()
    @Expose({ name: "chat" })
    chat?: string;

    /**
     * The few shot examples for the prompt
     */
    @SpeakeasyMetadata({ elemType: PromptCreationQueryFewShotExamples })
    @Expose({ name: "few_shot_examples" })
    @Type(() => PromptCreationQueryFewShotExamples)
    fewShotExamples?: PromptCreationQueryFewShotExamples[];

    /**
     * The hyperparameters for the prompt
     */
    @SpeakeasyMetadata()
    @Expose({ name: "hyperparameters" })
    hyperparameters?: Record<string, any>;

    /**
     * Flag indicating if the prompt is deployed
     */
    @SpeakeasyMetadata()
    @Expose({ name: "is_deployed" })
    isDeployed?: boolean;

    /**
     * The model to be used for the prompt
     */
    @SpeakeasyMetadata()
    @Expose({ name: "model" })
    model?: string;

    /**
     * The model provider
     */
    @SpeakeasyMetadata()
    @Expose({ name: "provider" })
    provider?: string;

    /**
     * The task for which the prompt is being created
     */
    @SpeakeasyMetadata()
    @Expose({ name: "task" })
    task?: string;

    /**
     * The text of the prompt
     */
    @SpeakeasyMetadata()
    @Expose({ name: "text" })
    text?: string;

    /**
     * The version of the prompt
     */
    @SpeakeasyMetadata()
    @Expose({ name: "version" })
    version?: string;
}
