/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Expose } from "class-transformer";

/**
 * The response object indicating the success of the tracing operation
 */
export class SuccessTraceResponse extends SpeakeasyBase {
    /**
     * The ID of the session
     */
    @SpeakeasyMetadata()
    @Expose({ name: "session_id" })
    sessionId?: string;

    /**
     * Indicates whether the request was successful
     */
    @SpeakeasyMetadata()
    @Expose({ name: "success" })
    success?: boolean;
}
