/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Expose, Type } from "class-transformer";

export class UploadDatasetFile extends SpeakeasyBase {}

/**
 * The request object for uploading a dataset
 */
export class UploadDataset extends SpeakeasyBase {
    /**
     * The description of the dataset
     */
    @SpeakeasyMetadata()
    @Expose({ name: "description" })
    description?: string;

    @SpeakeasyMetadata({ elemType: UploadDatasetFile })
    @Expose({ name: "file" })
    @Type(() => UploadDatasetFile)
    file?: UploadDatasetFile[];

    /**
     * The name of the dataset
     */
    @SpeakeasyMetadata()
    @Expose({ name: "name" })
    name?: string;

    /**
     * The prompt related to the dataset
     */
    @SpeakeasyMetadata()
    @Expose({ name: "prompt" })
    prompt?: string;

    /**
     * The purpose of the dataset
     */
    @SpeakeasyMetadata()
    @Expose({ name: "purpose" })
    purpose?: string;

    /**
     * The task related to the dataset
     */
    @SpeakeasyMetadata()
    @Expose({ name: "task" })
    task?: string;
}
